### PR TITLE
Passes

### PR DESCRIPTION
**Pull request by suhr**

### CODE REVIEW

**Comment by suhr** [comment]
It looks like the github version of rust is somewhat out of date. Travis CI version is fresh though.

**Comment by kpp** [comment]
Will fix tomorrow

**Comment by kpp** [comment]
Fixed in https://github.com/suhr/razbor/pull/7

**Comment by suhr** [comment]
> cargo fmt

I never asked for this.

**Comment by kpp** [comment]
I can remove fmt check. Still this suggestion by fmt looks reasonable:

```diff
-                }
-                else {
+                } else {
                     new.push(e)
                 }
```

**Comment by suhr** [comment]
It's a matter of taste actually.

**Comment by kpp** [comment]
https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#control_brace_style "ClosingNextLine"

**Comment by suhr** [comment]
> Stable: No (tracking issue: #3377)

As usually with rustfmt, sane formatting is either not stable, or [unavailable](https://github.com/rust-lang/rustfmt/issues/3208) or *is not possible under rustfmt's model*.

**Comment by kpp** [comment]
What do you suggest then?

**Comment by suhr** [comment]
Get rid of rustfmt until it becomes usable or until there's a nuclear style war.

**Pull request merged**
